language: php

# run tests on php 5.5 only and let unit / integration tests deal with php differences
php:
  - 5.5

# list of paths/bundle to execute
env:
    # run setup wizard to install Demo+Content and then test demo with content
  - INSTALL="demoContentNonUniqueDB" PROFILE="demo" TEST="content"
    # test Legacy
  - INSTALL="demoCleanNonUniqueDB" PROFILE="legacyAdmin" TEST="full"
    # test REST
  - INSTALL="demoCleanNonUniqueDB" PROFILE="rest" TEST="fullJson"
  - INSTALL="demoCleanNonUniqueDB" PROFILE="rest" TEST="fullXml"


# test only master (+ Pull requests)
branches:
  only:
    - master

# install packages
before_install:
  - ./bin/.travis/prepare_system.sh
  - ./bin/.travis/prepare_sahi.sh
#  - ./bin/.travis/prepare_selenium2.sh

# setup requirements for running tests
before_script:
  - ./bin/.travis/prepare_ezpublish.sh

# execute behat as the script command
script:
    - sudo apt-get install tree
    - tree vendor/ezsystems/behatbundle/EzSystems/BehatBundle/
    - tree vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishRestBundle/Features
    - tree vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishLegacyBundle/Features
    - php bin/behat --profile setupWizard --suite $INSTALL
    - php bin/behat --profile $PROFILE --suite $TEST

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
