parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    # The session name.
    # Using "{siteaccess_hash}" in the session name will make the session relative to the siteaccess.
    session_name: "eZSESSID{siteaccess_hash}"

    ezpublish_legacy.view.default_layout: eZDemoBundle::pagelayout.html.twig
